[target.aarch64-linux-android]
linker = "F:/AutoGram/.toolchains/android-sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android26-clang.cmd"

[build]
target = "aarch64-linux-android"
