name: Auto‑update update.json on Release

# Beri token write access
permissions:
  contents: write

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout main branch dengan token & simpan kredensial
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true     # penting: simpan GITHUB_TOKEN ke git
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2) Generate release_data.json
      - name: Generate release_data.json
        uses: actions/github-script@v6
        with:
          script: |
            const r = context.payload.release;
            const tag = r.tag_name;
            const d = new Date(r.published_at);
            const versionCode = `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;
            const zip = (r.assets.find(a=>a.name.endsWith('.zip'))||{}).browser_download_url || '';
            const type = r.prerelease ? 'beta' : 'stable';
            require('fs').writeFileSync('release_data.json',
              JSON.stringify({ version: tag, versionCode, zipUrl: zip, releaseType: type }, null,2)
            );

      # 3) (Opsional) Debug
      - name: Show release_data.json
        run: cat release_data.json

      # 4) Update update.json
      - name: Update update.json
        run: |
          VERSION=$(jq -r '.version' release_data.json)
          VERSION_CODE=$(jq -r '.versionCode' release_data.json)
          ZIP_URL=$(jq -r '.zipUrl' release_data.json)
          RELEASE_TYPE=$(jq -r '.releaseType' release_data.json)

          jq \
            --arg version "$VERSION" \
            --argjson versionCode "$VERSION_CODE" \
            --arg zipUrl "$ZIP_URL" \
            --arg releaseType "$RELEASE_TYPE" \
            '.version     = $version |
             .versionCode = $versionCode |
             .zipUrl      = $zipUrl |
             .releaseType = $releaseType' \
            update.json > update.json.tmp && mv update.json.tmp update.json

      # 5) Commit & push ke main
      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add update.json
          git commit -m "Auto‑update update.json for $VERSION" || echo "No changes to commit"
          git push
